SELECT * FROM TB_CLIENTES;

SELECT TO_CHAR(DATA_NASCIMENTO, 'MM') FROM TB_CLIENTES;

SELECT PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA FROM TB_PRODUTOS

SELECT PRECO_LISTA, NOME, PRODUTO, EMBALAGEM, TAMANHO, SABOR FROM TB_PRODUTOS

SELECT PRODUTO, NOME FROM TB_PRODUTOS

SELECT PRODUTO AS "CODIGO DO PRODUTO", NOME AS "NOME DO PRODUTO", EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA FROM TB_PRODUTOS

SELECT PRODUTO AS "CODIGO DO PRODUTO", 
             NOME AS "NOME DO PRODUTO", 
             EMBALAGEM, TAMANHO, 
             SABOR, 
             PRECO_LISTA FROM TB_PRODUTOS; 


--Filtros

SELECT * FROM TB_PRODUTOS WHERE PRODUTO = '1040107';
SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Melancia';

UPDATE TB_PRODUTOS SET SABOR = 'Citricos' WHERE PRODUTO = '1088126';
UPDATE TB_PRODUTOS SET SABOR = 'Citricos' WHERE PRODUTO = '544931';
UPDATE TB_PRODUTOS SET SABOR = 'Citricos' WHERE SABOR = 'Limao'; 

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Limao';
SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Citricos';

SELECT * FROM TB_CLIENTES WHERE IDADE = 22;
SELECT * FROM TB_CLIENTES WHERE IDADE > 22;
SELECT * FROM TB_CLIENTES WHERE IDADE >= 22;
SELECT * FROM TB_CLIENTES WHERE IDADE <= 22;
SELECT * FROM TB_CLIENTES WHERE IDADE <> 22;

SELECT * FROM TB_CLIENTES WHERE NOME > 'Marcelo Mattos'
SELECT * FROM TB_CLIENTES WHERE NOME <> 'Marcelo Mattos'

SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA > 16.008;
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA = 16.008;

SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO = '25/03/92';
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO = TO_DATE('25/03/1992', 'DD/MM/YYYY');
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO = TO_DATE('03/25/1992', 'MM/DD/YYYY');
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO > TO_DATE('03/25/1992', 'MM/DD/YYYY');
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO < TO_DATE('03/25/1992', 'MM/DD/YYYY');
SELECT * FROM TB_CLIENTES WHERE TO_CHAR(DATA_NASCIMENTO, 'MM') = 9;

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA >= 16;
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA >= 16 AND PRECO_LISTA <=21;
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA > 16 AND SABOR = 'Laranja';
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA > 16 OR SABOR = 'Laranja';

SELECT * FROM TB_CLIENTES WHERE (IDADE >= 18 AND SEXO = 'F');
SELECT * FROM TB_CLIENTES WHERE (IDADE >= 18 AND SEXO = 'F') AND BAIRRO = 'Jardins';
SELECT * FROM TB_CLIENTES WHERE IDADE >= 18 AND SEXO = 'F' AND BAIRRO = 'Jardins';

SELECT * FROM TB_CLIENTES WHERE (IDADE >= 18 AND SEXO = 'F') 
AND (CIDADE = 'Sao Paulo' OR BAIRRO = 'Barra da Tijuca');

SELECT * FROM TB_CLIENTES WHERE (IDADE >= 18 AND SEXO = 'F' 
AND CIDADE = 'Sao Paulo') OR BAIRRO = 'Barra da Tijuca';

SELECT * FROM TB_VENDEDORES WHERE PERCENTUAL_COMISSAO <0.15 OR PERCENTUAL_COMISSAO >0.19;
