--Função categoria
CREATE OR REPLACE FUNCTION categoria_cliente
    (p_FATURAMENTO_PREVISTO IN CLIENTE.FATURAMENTO_PREVISTO%type) 
RETURN CLIENTE.CATEGORIA%type
IS
    v_CATEGORIA CLIENTE.CATEGORIA%type;
BEGIN
     IF P_FATURAMENTO_PREVISTO < 10000 THEN
        v_CATEGORIA := 'PEQUENO';
    ELSIF P_FATURAMENTO_PREVISTO < 50000 THEN
        v_CATEGORIA := 'MÉDIO';
    ELSIF P_FATURAMENTO_PREVISTO < 100000 THEN
        v_CATEGORIA := 'MÉDIO GRANDE';
    ELSE
        v_CATEGORIA := 'GRANDE';
    END IF;  
    RETURN v_CATEGORIA;
END;
      
VARIABLE g_CATEGORIA VARCHAR2(100);

EXECUTE :g_CATEGORIA := categoria_cliente(110000);

PRINT g_CATEGORIA;
