--Formatando retordo dos dados
SELECT * FROM CLIENTE;
SELECT SUBSTR(CNPJ,1,3) || '-' || SUBSTR(CNPJ,4,2) FROM CLIENTE;


CREATE OR REPLACE PROCEDURE formata_cnpj
    (p_CNPJ IN CLIENTE.CNPJ%type, p_CNPJ_SAIDA OUT CLIENTE.CNPJ%type) 
IS
BEGIN
    p_CNPJ_SAIDA := SUBSTR(p_CNPJ,1,3) || '-' || SUBSTR(p_CNPJ,4,2);
END;
      
VARIABLE g_CNPJ VARCHAR2(10)
VARIABLE g_CNPJ_SAIDA VARCHAR2(10)

EXECUTE :g_CNPJ := '12345'
PRINT :g_CNPJ

EXECUTE formata_cnpj(:g_CNPJ, :g_CNPJ_SAIDA)

PRINT :g_CNPJ
PRINT :g_CNPJ_SAIDA

--MELHORANDO A CRIAÇÃO DA PROCEDURE
CREATE OR REPLACE PROCEDURE formata_cnpj
    (p_CNPJ IN OUT CLIENTE.CNPJ%type) 
IS
BEGIN
    p_CNPJ := SUBSTR(p_CNPJ,1,3) || '-' || SUBSTR(p_CNPJ,4,2);
END;
      
VARIABLE g_CNPJ VARCHAR2(10)

EXECUTE :g_CNPJ := '12345'
PRINT :g_CNPJ

EXECUTE formata_cnpj(:g_CNPJ)

PRINT :g_CNPJ
